apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-orders
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: db-orders
  template:
    metadata:
      labels:
        app: db-orders
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
          volumeMounts:
            - name: db-storage-orders
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage-orders
          persistentVolumeClaim:
            claimName: db-pvc-orders