apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-orders
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}