apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MSPR-EPSI-24-26/software-factory.git
    targetRevision: main
    path: customers/chart
    helm:
      valueFiles:
        - ../values/prod-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: payetonkawa-prod
  ignoreDifferences:
    - group: apps
      kind: Deployment
      namespace: payetonkawa-prod
      jsonPointers:
        - /spec/replicas