apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-preprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MSPR-EPSI-24-26/software-factory.git
    path: customers/manifests/preprod
  destination:
    server: https://kubernetes.default.svc
    namespace: payetonkawa-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
