apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: payetonkawa-prod
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend-app
          image: ghcr.io/mspr-epsi-24-26/front:f75e246a936a4e2e38ec4a207f4dbafe58d8cdb3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: NEXT_PUBLIC_API_CUSTOMER_URL
              value: https://customers.payetonkawa.shop
            - name: NEXT_PUBLIC_API_ORDERS_URL
              value: https://orders.payetonkawa.shop
            - name: NEXT_PUBLIC_API_PRODUCTS_URL
              value: https://products.payetonkawa.shop
            - name: NEXT_PUBLIC_API_MESSAGE_BROKER_URL
              value: https://message-broker.payetonkawa.shop
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi