apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: payetonkawa-prod
spec:
  type: ClusterIP
  selector:
    app: frontend-app
  ports:
    - port: 3014
      targetPort: 3000