apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: payetonkawa-prod
spec:
  type: ClusterIP
  ports:
    - port: 3010
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana