apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-customers
  namespace: payetonkawa-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-customers
  template:
    metadata:
      labels:
        app: db-customers
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "api_customers"
          volumeMounts:
            - name: db-storage-customers
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: db-storage-customers
          persistentVolumeClaim:
            claimName: db-pvc-customers