apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-customers
  namespace: api-customers
  labels:
    app: api-customers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-customers
  template:
    metadata:
      labels:
        app: api-customers
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api-customers
          image: ghcr.io/mspr-epsi-24-26/api-customers:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"