apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
  namespace: payetonkawa-prod
  labels:
    app: message-broker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: message-broker
          image: ghcr.io/mspr-epsi-24-26/message-broker:f3c927e480e775b4bb0db29676e276000c774f74
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3003"
            - name: RABBITMQ_URL
              value: "amqp://admin:admin123@rabbitmq-service:5672"
          