apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: message-broker
  labels:
    app: rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: NODE_ENV
              value: "production"
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin123"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: db-pvc-rabbitmq