apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: message-broker
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      tagetPort: 15672
      name: management