apiVersion: v1
kind: Service
metadata:
  name: api-message-broker-service
  namespace: message-broker
spec:
  type: ClusterIP
  selector:
    app: message-broker
  ports:
    - port: 3003
      targetPort: 3003