apiVersion: v1
kind: Service
metadata:
  name: db-service-products
  namespace: payetonkawa-prod
spec:
  selector:
    app: db-products
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP