apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-products
  namespace: payetonkawa-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi