apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-products
  namespace: payetonkawa-prod
  labels:
    app: api-products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-products
  template:
    metadata:
      labels:
        app: api-products
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api-products
          image: ghcr.io/mspr-epsi-24-26/api-products:6c8e6b52db1c90a52a0fb747d4a4742b6550dc1c
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3002"
            - name: DATABASE_HOST
              value: "db-service-products"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "api_products"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi