apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-products
  namespace: api-products
  labels:
    app: api-products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-products
  template:
    metadata:
      labels:
        app: api-products
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api-products
          image: ghcr.io/mspr-epsi-24-26/api-products
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: DATABASE_HOST
              value: "db-service"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "api_products"