apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-products-ingress
  namespace: payetonkawa-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: products.payetonkawa.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-products-service
                port:
                  number: 3002
