namespace: payetonkawa-preprod
replicas: 1
image:
  repository: ghcr.io/mspr-epsi-24-26/api-customers
  tag: dev
  policy: Always
  port: 3000
ingress:
  host: customer.preprod.payetonkawa.shop
db:
  replicas: 1
volume:
  storage: 2Gi