namespace: payetonkawa-prod
replicas: 3
image:
  repository: ghcr.io/mspr-epsi-24-26/api-customers
  tag: d92fe8a902d451b2a2f4f625aaea10c37a3eef6e
  policy: Always
  port: 3000
ingress:
  host: customer.payetonkawa.shop
db:
  replicas: 2
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2
    memory: 2Gi
volume:
  storage: 2Gi
deploy:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi
hpa:
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 50