apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-customers
  namespace: payetonkawa-preprod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi