apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: payetonkawa-prod
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 3011
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
