apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-orders
  namespace: api-orders
  labels:
    app: api-orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-orders
  template:
    metadata:
      labels:
        app: api-orders
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api-orders
          image: ghcr.io/mspr-epsi-24-26/api-orders:d1db2f471b353274d87f421948d23cf9d25dc927
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: DATABASE_HOST
              value: "db-service-orders"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "api_orders"