apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-orders
  namespace: payetonkawa-prod
  labels:
    app: api-orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-orders
  template:
    metadata:
      labels:
        app: api-orders
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api-orders
          image: ghcr.io/mspr-epsi-24-26/api-orders:a90912020c11ce5d3760689ff060d902e73ef032
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3001"
            - name: DATABASE_HOST
              value: "db-service-orders"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "api_orders"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi