apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-customers
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: db-customers
  template:
    metadata:
      labels:
        app: db-customers
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
          volumeMounts:
            - name: db-storage-customers
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: {{ .Values.db.requests.cpu }}
              memory: {{ .Values.db.requests.memory }}
            limits:
              cpu: {{ .Values.db.limits.cpu }}
              memory: {{ .Values.db.limits.memory }}
      volumes:
        - name: db-storage-customers
          persistentVolumeClaim:
            claimName: db-pvc-customers