apiVersion: v1
kind: Service
metadata:
  name: api-customers-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: api-customers
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.targetPort }}